language: generic

before_install:
  - sudo apt-get install python-pygments

install:
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - cd $TRAVIS_BUILD_DIR/term-project/proposal/
  - pdflatex --shell-escape ./grifski-term-project-proposal.tex
  - pdflatex --shell-escape ./grifski-term-project-proposal.tex
  - cd $TRAVIS_BUILD_DIR/midterm-project/docs/
  - pdflatex --shell-escape ./assignment01.tex
  - pdflatex --shell-escape ./assignment01.tex
  - cd $TRAVIS_BUILD_DIR/term-project/report/
  - pdflatex --shell-escape ./report.tex
  - pdflatex --shell-escape ./report.tex

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file:
    - $TRAVIS_BUILD_DIR/term-project/proposal/grifski-term-project-proposal.pdf
    - $TRAVIS_BUILD_DIR/midterm-project/docs/assignment01.pdf
    - $TRAVIS_BUILD_DIR/term-project/report/report.pdf

  skip_cleanup: true
  on:
    tags: true
    branch: master

notifications:
  email: false
